### ISSUE TITLE
References for Trends

### ISSUE THREAD

**Issue by creeas** [coffeejunk/sharkT#540]
Hey @coffeejunk thanks for sending along the exported refs from the trends side of the database. As I was compiling them to include in a zenodo repository along with our paper I noticed an issue. It looks like the trends were coded by Nathan and the trends team as `Author_Year` while on the traits side we coded them as `AuthorYear`. In going through the list that you sent I can see that Sharkipedia is assigning refs to each trend based on the traits coding. So with this mismatch the trends are being assigned to the wrong references. 

<img width="1367" alt="Screen Shot 2022-02-11 at 12 00 19 PM" src="https://user-images.githubusercontent.com/4634830/153713329-f86d4d52-5f3c-4e14-8e53-874b0a1d9e20.png">

<img width="1415" alt="Screen Shot 2022-02-11 at 12 00 41 PM" src="https://user-images.githubusercontent.com/4634830/153713351-b0a17f2a-1ea5-4352-b12f-8113a3a6221c.png">

For example, take trend 2380 from the `trend-sources.csv` file you sent. According to this is is assigned to `author_year: Kyne2007`  and `data_source: Shark-reference`, but according to the trends file that Nathan compiled this is `Kyne_2007` with the `data_source: Kyne, P. M., & Simpfendorfer, C. A. (2007). A collation and summarization of available data on deepwater chondrichthyans: Biodiversity, life history and fisheries: A report prepared for th IUCN SSC Shark Specialist Group for the Marine Conservation Biology Institute.` 

<img width="673" alt="Screen Shot 2022-02-11 at 12 01 04 PM" src="https://user-images.githubusercontent.com/4634830/153634671-352fd705-fa41-4fcd-a2f3-9acbeff755c0.png">

<img width="1406" alt="Screen Shot 2022-02-11 at 12 01 25 PM" src="https://user-images.githubusercontent.com/4634830/153637825-d821d3f7-c104-44d0-9d0b-4d1d4b3bb5e9.png">

The `kyne2007` from Shark-references is also what is filled in on the details page for this trend (https://www.sharkipedia.org/trends/2380). 

<img width="731" alt="Screen Shot 2022-02-11 at 12 57 25 PM" src="https://user-images.githubusercontent.com/4634830/153638089-6a5333aa-b8be-4940-b5e2-e27a04a47531.png">

I'm not sure if this is as simple a coding the trends refs as `Author_Year`? Also the issue might be that the trends reference list wasn't included in the intial reference list when we initialized the database, as at that point we had only included the Shark-references and additional traits sources. So if needed I can try and merge the initial traits and new trends together into a single reference database. Whichever route you think might be best.

**Comment by coffeejunk** [comment]
Hey @creeas, 

`Keyne2007` and `Keyne_2007` are the same reference [in the database](https://www.sharkipedia.org/references/kyne2007). The difference between the CSV files is just representation. If I remember correctly, we initially had the `_` and then moved to the `_`-less schema. 

The issue is that we had the reference already present in the database when Nathan uploaded the trends, and the importer doesn't update any existing references:

<img width="497" alt="Screen Shot 2022-02-15 at 8 17 53 PM" src="https://user-images.githubusercontent.com/205556/154177798-9ff48f0b-1a0f-4e78-ac53-32b162882094.png">

It only checks if a reference exists and if so, uses it. To remedy this, I'd have to update the references in the database.

**Comment by creeas** [comment]
Thanks @coffeejunk. I should still have the .csv file that the initial traits reference database was generated from (the full refs list from shark-refernces). Or maybe you have an updated list from when the database was initialized. I can add the trends references to then update the full reference database. Is that the easiest way forward? Otherwise just let me know what you need and I can get you any info you need.

**Comment by coffeejunk** [comment]
If you could get me a CSV file that lists:

```csv 
authoryear,reference
```

I can update the database.

**Comment by creeas** [comment]
10-4...sorry for the slow reply, but I will get this to you ASAP...

**Comment by creeas** [comment]
Hey @coffeejunk sorry for the long delay on this! I have just uploaded a new csv with the full ref list harmonized between traits and trends: `Docs/shark-resources-220503-duplicates removed.csv`. I have created a file for nathan to use to update the resource_id's that need correcting for trends. I think he can simply do this through the admin dashboard and I can help walk him through that. Should we try a isolated implementation of this before we launch the thing. Just let me know if you need anything else from me.
