### ISSUE TITLE
Upload not available for users

### ISSUE THREAD

**Issue by creeas** [coffeejunk/sharkT#710]
Hey @coffeejunk it seems that when someone is logged in as a user the option to upload data is not popping up. It looks like the 'Upload Data' drop down menu just isn't appearing for this class.

**Comment by coffeejunk** [comment]
Hey @creeas, this is a feature, not a bug. 🙃 

The `Upload Data` drop-down is only available if the user is a `contributor` (we have `user`, `contributor`, `editor`, and `admin`). That said, I can change this to also allow `user`s to upload data if you'd prefer that.
