### ISSUE TITLE
Adding New Trait Class: Ecological Role

### ISSUE THREAD

**Issue by creeas** [coffeejunk/sharkT#954]
Hey @coffeejunk and @redrambles I'm going to add a new trait class on ecological roles and the required sub-fields. I was planning on doing this through the admin dashboard, but was wondering if this is the best way to implement this?

**Comment by coffeejunk** [comment]
Hey @creeas, that sounds like the right way to go about it. If you want to test-drive the changes, you can do so on [staging](https://sharkipedia-staging.herokuapp.com/).

**Comment by creeas** [comment]
Great! Thanks @coffeejunk

**Comment by creeas** [comment]
Additionally we will have to add a few new refs to the db as this is a newer field of research and most refs have come out since we last scraped the shark-references db. Is there a method to import multiple refs as with the traits or do we need to enter each ref individually though the refs import UI?

**Comment by coffeejunk** [comment]
We don't have anything for bulk imports that covers all the new fields for references. Do you have the references already in a CSV, or where are you getting the data from?

**Comment by creeas** [comment]
We have the refs in a csv file. Just wondering if we could import that to the db or if we should do them all manually.

**Comment by coffeejunk** [comment]
If it's already a CSV, we can probably import it. Can you upload it here or send it to me via email?

**Comment by creeas** [comment]
[sharki-refs-to-upload.xlsx](https://github.com/sharkipedia/sharkipedia/files/12140779/sharki-refs-to-upload.xlsx)

Hey @coffeejunk sorry I was away at a conference but here is the csv with the refs to upload. There are a small number for which I could not find a DOI so these fields are blank. Let me know if we can mange a bulk import or I can drudge through these one at a time. Thanks!

**Comment by creeas** [comment]
Hey @coffeejunk and @redrambles just wanted to quickly check if we can do a bulk import of refs? Thanks!

**Comment by coffeejunk** [comment]
@creeas we've just imported the references.

**Comment by creeas** [comment]
Thanks a ton @coffeejunk and @redrambles !

**Comment by creeas** [comment]
Hey @coffeejunk and @redrambles the admin dashboard worked perfectly for adding a new trait class, traits, and standards. Thanks a ton! Now I will get back to the shapefile rendering for you...
